# Generated by Django 5.2.4 on 2026-01-19 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('left', 'Left'), ('Left', 'Left'), ('right', 'Right'), ('Right', 'Right')], max_length=10)),
                ('duration', models.DurationField()),
                ('airport_code_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='airport_route.airport')),
                ('airport_code_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='airport_route.airport')),
            ],
        ),
    ]
