# Generated by Django 5.2.4 on 2026-01-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='route',
            name='position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5),
        ),
    ]
